export enum ColumnActionsType {
  ADD_CARD = "ADD_CARD",
  EDIT_CARD = "EDIT_CARD",
  DELETE_CARD = "DELETE_CARD",
  ADD_COLUMN = "ADD_COLUMN",
  SET_COLUMN_TITLE = "SET_COLUMN_TITLE",
  DRAG_OVER = "DRAG_OVER",
  DRAG_END = "DRAG_END",
  DELETE_COLUMN = "DELETE_COLUMN",
  FILTER_CARDS = "FILTER_CARDS",
}
